### PR TITLE
set shell to powershell

### PR DESCRIPTION
**Pull request by diamant3**
according to this https://github.com/ScoopInstaller/Install?tab=readme-ov-file#typical-installation for non-admin

### CODE REVIEW

**Comment by HendrixString** [comment]
@diamant3 ,

Nice, so now I made some changes to cmake commands,
adding sudo and some changes and I was able to compile examples.
It is failing for osx and linux due to bad examples I have in there, which
is good news because I can fix them

**Comment by diamant3** [comment]
that's great to hear, let me know if you need some help, thanks for accepting my proposal!

**Comment by HendrixString** [comment]
@diamant3 Yes there is something else I want, that you can help with:

I want to add another target `Linux with Clang++` compiler (like in OSX). g++ is so different from clang and
I might not support it, because it might not compile the project

**Comment by diamant3** [comment]
got it, but I think it needs to set the CC or something in compiler to set in clang++ but my level of experience in cmake is low, can you help me with that?

**Comment by diamant3** [comment]
for full disclosure I forgot to say, sorry. I'm using Ubuntu in WSL

**Comment by HendrixString** [comment]
@diamant3 Don't stress about it,
I believe that we don't need it.
I was able to compile locally using g++, so we are on the right track

**Pull request merged**
